#!/usr/bin/env python3
"""Generate human-readable calculation documentation from the live formulas.

The country modules remain the source of truth. This script turns their metadata,
module notes, constants, functions, and current generated outputs into Markdown so
the explanation cannot quietly diverge from the implementation.

Usage:
    python3 tools/generate_calculation_docs.py
    python3 tools/generate_calculation_docs.py --check
"""

import argparse
import ast
import hashlib
import importlib
import json
import pprint
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
CALC_DIR = ROOT / "tools" / "calc"
DOCS_DIR = ROOT / "docs" / "calculations"
INDEX_PATH = DOCS_DIR / "README.md"
US_DOCS_DIR = DOCS_DIR / "us"
US_INDEX_PATH = US_DOCS_DIR / "README.md"
FORMULA_PATH = ROOT / "data" / "formula.json"
US_DATA_PATH = ROOT / "data" / "us.json"
SKIP_CONSTANTS = {
    "NAME", "CURRENCY", "YEAR", "LAST_REVIEWED", "EMPLOYER_BREAKDOWN", "INF"
}


def slug(name):
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def euro(amount):
    return f"€{amount:,.0f}"


def module_assignments(tree, source):
    """Return exact source for public calculation constants in declaration order."""
    blocks = []
    for node in tree.body:
        if not isinstance(node, (ast.Assign, ast.AnnAssign)):
            continue
        targets = node.targets if isinstance(node, ast.Assign) else [node.target]
        names = []
        for target in targets:
            if isinstance(target, ast.Name):
                names.append(target.id)
            elif isinstance(target, (ast.Tuple, ast.List)):
                names.extend(item.id for item in target.elts if isinstance(item, ast.Name))
        if names and any(name.isupper() and name not in SKIP_CONSTANTS for name in names):
            blocks.append(ast.get_source_segment(source, node))
    return "\n".join(blocks)


def module_functions(tree, source):
    """Return the exact helper and compute functions used by a country module."""
    return "\n\n".join(
        ast.get_source_segment(source, node)
        for node in tree.body
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
    )


def selected_assignments(tree, source, names):
    """Return exact assignment source for requested top-level names."""
    blocks = []
    for node in tree.body:
        if not isinstance(node, (ast.Assign, ast.AnnAssign)):
            continue
        targets = node.targets if isinstance(node, ast.Assign) else [node.target]
        assigned = {target.id for target in targets if isinstance(target, ast.Name)}
        if assigned & names:
            blocks.append(ast.get_source_segment(source, node))
    return "\n".join(blocks)


def selected_functions(tree, source, names):
    """Return exact source for requested top-level functions."""
    return "\n\n".join(
        ast.get_source_segment(source, node)
        for node in tree.body
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name in names
    )


def source_links(text):
    return re.findall(r"https?://[^\s)>]+", text)


def benchmark_rows(country):
    wanted = (60_000, 100_000, 200_000)
    by_gross = {point["gross"]: point for point in country["points"]}
    rows = []
    for gross in wanted:
        point = by_gross.get(gross)
        if point:
            rows.append(
                f"| {euro(gross)} | {euro(point['cost'])} | {euro(point['net'])} |"
            )
    return "\n".join(rows)


def country_page(module, path, country):
    source = path.read_text(encoding="utf-8")
    tree = ast.parse(source)
    notes = ast.get_docstring(tree, clean=True) or "No model notes recorded."
    links = source_links(notes)
    link_note = (
        "<br>".join(f"[{url}]({url})" for url in links)
        if links
        else "Named in the model notes below; direct URLs have not yet been recorded."
    )
    fingerprint = hashlib.sha256(source.encode()).hexdigest()[:12]
    parameters = module_assignments(tree, source)
    functions = module_functions(tree, source)
    relative_source = f"../../tools/calc/{path.name}"

    return f"""<!-- Generated by tools/generate_calculation_docs.py; do not edit directly. -->

# {country['flag']} {module.NAME}

[← All country calculations](README.md) · [Formula source]({relative_source})

| Field | Value |
|---|---|
| Tax year | {module.YEAR} |
| Last independently reviewed | {getattr(module, 'LAST_REVIEWED', 'Not recorded')} |
| Calculation currency | {module.CURRENCY} |
| Model | Single employee; see assumptions below |
| Employer-cost summary | {module.EMPLOYER_BREAKDOWN} |
| Formula fingerprint | `{fingerprint}` |
| Direct source links | {link_note} |

## Representative outputs

These are the current website outputs in euros, after the build-time currency
conversion where applicable. They are regression landmarks, not payroll quotes.

| Annual gross | Employer cost | Take-home pay |
|---:|---:|---:|
{benchmark_rows(country)}

## Model notes and assumptions

{notes}

## Implemented parameters

These values are copied mechanically from the live calculation module.

```python
{parameters}
```

## Executable calculation

This is the exact function used to build the salary dataset. Shared progressive
tax brackets use [`engine.progressive`](../../tools/calc/engine.py).

```python
{functions}
```

## Verification checklist

- Confirm the tax year and filing profile still match the intended model.
- Follow the cited authority names and links; add direct URLs to the module when missing.
- Check every rate, bracket, cap, allowance, deduction, and employer charge.
- Confirm whether employee contributions reduce the income-tax base.
- Compare the representative outputs above with an official worked example.
- Update the module, regenerate the Formula dataset and these docs, then review the diff.
"""


def us_charge_summary(cfg):
    """Return a readable summary of a city's configured deductions and costs."""
    parts = ["Federal income tax and employee FICA"]
    income = cfg.get("income")
    if income is None:
        parts.append("no state income tax")
    elif income[0] == "flat":
        parts.append(
            f"{income[1]:.2%} flat state income tax after a ${income[2]:,.0f} deduction"
        )
    else:
        parts.append(
            f"progressive state income tax after a ${income[1]:,.0f} deduction"
        )
    if cfg.get("local"):
        parts.append("progressive NYC resident income tax")
    if cfg.get("sdi"):
        cap = " capped at the Social Security wage base" if cfg.get("sdi_capped") else " uncapped"
        parts.append(f"{cfg['sdi']:.2%} employee paid-leave/disability contribution{cap}")
    if cfg.get("head_tax"):
        parts.append("Denver employee and employer occupational privilege tax")
    parts.append("employer FICA, FUTA, and representative new-employer SUTA")
    return "; ".join(parts) + "."


def us_city_page(calc_us, city, state, country, us_meta):
    cfg = calc_us.STATES[state]
    implementation = (ROOT / "tools" / "calc_us.py").read_text(encoding="utf-8")
    fingerprint_source = implementation + repr((state, cfg))
    fingerprint = hashlib.sha256(fingerprint_source.encode()).hexdigest()[:12]
    config = pprint.pformat(cfg, sort_dicts=False, width=88)
    return f"""<!-- Generated by tools/generate_calculation_docs.py; do not edit directly. -->

# 🇺🇸 {city}

[← All calculations](../README.md) · [US methodology](README.md) · [Formula source](../../../tools/calc_us.py)

| Field | Value |
|---|---|
| Tax year | {us_meta['year']} |
| Last independently reviewed | Not recorded |
| Calculation jurisdiction | {state} |
| Calculation currency | USD; website output converted to EUR |
| Build exchange rate | 1 EUR = {us_meta['fxEurUsd']:.4f} USD |
| Formula fingerprint | `{fingerprint}` |
| Direct source links | Not recorded in `tools/calc_us.py` |

## Representative outputs

These are the current website outputs in euros after build-time currency
conversion. They are regression landmarks, not payroll quotes.

| Annual gross | Employer cost | Take-home pay |
|---:|---:|---:|
{benchmark_rows(country)}

## What is calculated

{us_charge_summary(cfg)}

The model assumes a single filer using the standard deduction, with no dependents,
credits, itemized deductions, benefits, or workers' compensation. See the
[shared US methodology](README.md) for the exact federal parameters and executable
calculation used with this location configuration.

## State and local configuration

This is the exact configuration passed to the shared calculation for {city}.

```python
{config}
```

## Verification checklist

- Confirm the federal and {state} rules still apply for tax year {us_meta['year']}.
- Verify the state deduction, brackets or flat rate, and any city income tax.
- Verify employee disability or paid-leave charges and their wage caps.
- Verify the representative new-employer SUTA rate and taxable wage base.
- Add direct official source URLs and review metadata to `calc_us.py`.
- Compare the representative outputs with authoritative paycheck examples.
"""


def us_index_page(calc_us, records, us_meta):
    source = (ROOT / "tools" / "calc_us.py").read_text(encoding="utf-8")
    tree = ast.parse(source)
    constants = selected_assignments(tree, source, {
        "FED_STD_DEDUCTION", "FED_BRACKETS", "SS_RATE", "SS_WAGE_BASE",
        "MEDICARE_RATE", "ADD_MEDICARE_RATE", "ADD_MEDICARE_THRESHOLD", "FUTA",
    })
    functions = selected_functions(tree, source, {
        "progressive", "state_income_tax", "local_tax", "employee_fica",
        "employer_payroll", "compute",
    })
    rows = []
    for city, state, _country, page in records:
        cfg = calc_us.STATES[state]
        local = []
        if cfg.get("local"):
            local.append("NYC income tax")
        if cfg.get("sdi"):
            local.append("employee leave/disability levy")
        if cfg.get("head_tax"):
            local.append("Denver OPT")
        rows.append(
            f"| 🇺🇸 [{city}]({page.name}) | {state} | {'; '.join(local) or 'None'} |"
        )

    return f"""<!-- Generated by tools/generate_calculation_docs.py; do not edit directly. -->

# United States calculation methodology

[← All calculations](../README.md) · [Formula source](../../../tools/calc_us.py)

The 11 US entries share one federal and payroll-tax implementation, then apply a
state configuration and, where relevant, city-specific tax. Calculations run in
USD and the generated website dataset converts them to EUR using the build-time
rate of **1 EUR = {us_meta['fxEurUsd']:.4f} USD**.

## Cities

| City | State or district | Additional local/employee levy |
|---|---|---|
{chr(10).join(rows)}

## Scope and assumptions

- Tax year: **{us_meta['year']}**.
- Single filer using the standard deduction; no dependents, credits, or itemizing.
- Employee deductions include federal, state and applicable city income tax,
  employee FICA, and configured employee disability/paid-leave contributions.
- Employer cost includes employer FICA, FUTA, representative new-employer SUTA,
  and Denver OPT where applicable.
- Benefits, workers' compensation, and employer paid-leave premiums in WA/DC are
  excluded because they vary or sit outside this model's defined payroll-tax scope.
- SUTA rates vary by employer; the configured rates are representative estimates.
- Direct official source URLs and an independent review date are not yet recorded.

## Shared federal parameters

```python
{constants}
```

## Executable calculation

```python
{functions}
```

## Maintenance

When US rules change, update `tools/calc_us.py`, rebuild `data/us.json`, refresh
the US entries in `data/formula.json`, and regenerate these pages. The documentation
check will fail in CI if implementation or outputs drift.
"""


def index_page(records, us_records, us_meta):
    rows = []
    for module, path, country, page in records:
        source = path.read_text(encoding="utf-8")
        links = len(source_links(ast.get_docstring(ast.parse(source), clean=True) or ""))
        linked = str(links) if links else "Not recorded"
        reviewed = getattr(module, "LAST_REVIEWED", "Not recorded")
        rows.append(
            f"| {country['flag']} [{module.NAME}]({page.name}) | {module.YEAR} | "
            f"{reviewed} | {module.CURRENCY} | {linked} |"
        )
    return f"""<!-- Generated by tools/generate_calculation_docs.py; do not edit directly. -->

# Formula calculation reference

This reference documents the **actual formulas used by the website** for its 36
European countries and 11 US cities. Each page combines the model's assumptions
and source notes with exact parameters, executable logic or configuration, and
three representative outputs from the generated dataset.

The modules under [`tools/calc/`](../../tools/calc/) and the US implementation in
[`tools/calc_us.py`](../../tools/calc_us.py) remain the sources of truth. These
pages are generated from them, and CI fails if a formula changes without
regenerating the documentation.

The dated [primary-source audit](audits/2026-10-04-primary-source-audit.md)
separately records which rules have been independently checked, confirmed
discrepancies, and the remaining evidence backlog. Documentation of the current
implementation is not the same as validation of that implementation.

## Country index

| Country | Tax year | Last reviewed | Currency | Direct source URLs |
|---|---:|---:|:---:|---:|
{chr(10).join(rows)}

"Not recorded" means the module names its sources in prose but does not yet carry
a clickable source URL. It is an explicit documentation backlog—not evidence that
the formula has been freshly verified. The calculation pages preserve uncertainty
and representative assumptions instead of presenting estimates as statutory facts.
Review dates are likewise left unrecorded unless a maintainer has completed and
documented an independent review; add `LAST_REVIEWED = "YYYY-MM-DD"` to a country
module when that happens.

## US city index

The US entries share a federal/payroll implementation documented in the
[US calculation methodology](us/README.md), with a separate generated page for
each location.

| City | State or district | Tax year | Last reviewed |
|---|---|---:|---:|
{chr(10).join(f'| 🇺🇸 [{city}](us/{page.name}) | {state} | {us_meta["year"]} | Not recorded |' for city, state, _country, page in us_records)}

## Keeping calculations current

1. Review every jurisdiction before its new tax year takes effect.
2. Prefer primary tax/social-security authorities; record direct URLs and the
   official worked examples used for validation in the country module docstring.
3. Update the relevant module's tax year, review date, assumptions, constants,
   and formula together.
4. Add or update regression tests for thresholds and authoritative examples.
5. Rebuild data and documentation:

   ```bash
   python3 tools/calc_us.py
   python3 tools/build_formula.py
   python3 tools/generate_calculation_docs.py
   python3 -m unittest discover -s tests -v
   ```

6. Review the generated documentation diff. Changes to parameters, executable
   code, fingerprints, and representative outputs should all be explainable.

To check for stale generated pages without modifying files:

```bash
python3 tools/generate_calculation_docs.py --check
```

## Scope

The models assume a single employee and the location-specific profile described
on each page. Personal circumstances, regional variation, optional benefits, and
sector-specific charges are generally outside their scope. US city calculations
use the separate [`tools/calc_us.py`](../../tools/calc_us.py) implementation.
"""


def expected_files():
    sys.path.insert(0, str(CALC_DIR))
    formula = json.loads(FORMULA_PATH.read_text(encoding="utf-8"))
    countries = {item["name"]: item for item in formula["countries"] if not item.get("us")}
    records = []
    output = {}
    for path in sorted(CALC_DIR.glob("*.py")):
        if path.stem in {"engine", "__init__"}:
            continue
        module = importlib.import_module(path.stem)
        country = countries[module.NAME]
        page = DOCS_DIR / f"{slug(module.NAME)}.md"
        records.append((module, path, country, page))
        output[page] = country_page(module, path, country)

    sys.path.insert(0, str(ROOT / "tools"))
    calc_us = importlib.import_module("calc_us")
    us_doc = json.loads(US_DATA_PATH.read_text(encoding="utf-8"))
    us_countries = {item["name"]: item for item in us_doc["countries"]}
    us_records = []
    for city, state, _cost_of_living in calc_us.CITIES:
        country = us_countries[city]
        page = US_DOCS_DIR / f"{slug(city)}.md"
        us_records.append((city, state, country, page))
        output[page] = us_city_page(calc_us, city, state, country, us_doc["meta"])
    output[US_INDEX_PATH] = us_index_page(calc_us, us_records, us_doc["meta"])
    output[INDEX_PATH] = index_page(records, us_records, us_doc["meta"])
    return output, len(records), len(us_records)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated docs are stale")
    args = parser.parse_args()
    expected, country_count, city_count = expected_files()

    if args.check:
        stale = [path for path, content in expected.items()
                 if not path.exists() or path.read_text(encoding="utf-8") != content]
        if stale:
            print("Calculation documentation is stale:", file=sys.stderr)
            for path in stale:
                print(f"  {path.relative_to(ROOT)}", file=sys.stderr)
            print("Run: python3 tools/generate_calculation_docs.py", file=sys.stderr)
            return 1
        print(f"Calculation documentation is current ({country_count} countries, "
              f"{city_count} US cities).")
        return 0

    for path, content in expected.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    print(f"Wrote {country_count} country pages, {city_count} US city pages, and indexes.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
